stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
      - data_ingestion
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    params:
      - data_preprocessing
    outs:
    - data/processed

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
     - data/processed
     - src/feature_engineering.py
    params:
      - feature_engineering
    outs:
     - data/features
  
  model_building:
   cmd: python src/model_building.py
   deps:
   - data/features
   - src/model_building.py
   
   outs:
    - model/
  
  model_evaulation:
    cmd: python src/model_evaluation.py
    deps:
     - model/
     - src/model_evaluation.py
    
    outs:
      - output
